### ISSUE TITLE
No Image in front-end from image database 

### ISSUE THREAD

**Issue by sagar-spkt** [sagar-spkt/VibeBeats#1]
![screenshot 12](https://user-images.githubusercontent.com/22609549/33265122-84c95ca0-d398-11e7-886b-f85658dd7137.png)
According to the tutorial TheNewBoston tutorial 33
[https://youtu.be/v5FWAxi5QqQ?list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK](url)
`<img src="{{ MEDIA_ROOT }}{{ album.album_logo.url }}" class="img-responsive">`
this should show uploaded image in ('media/' folder) to  our website front-end

> Possible Error Places

settings.py
`MEDIA_ROOT = os.path.join(BASE_DIR, 'media')`
`MEDIA_URL = '/media/'`
VibeBeats/urls.py
`if settings.DEBUG:`
 `   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)`
 `   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)`

I added the database using admin with image which in uploaded to `/media/` folder 
and Image explain the rest.

**Comment by skshetry** [comment]
Add a `$`. 

Change
      `url(r'^', RedirectView.as_view(url='/music/',  permanent=False))`

to 
    `url(r'^$', RedirectView.as_view(url='/music/', permanent=False))`.
And, it should work.
